### ISSUE TITLE
Cant use nmap output

### ISSUE THREAD

**Issue by xcapri** [justakazh/sicat#1]
the command I use 
```
nmap -sV myip -oX nmap_out_single
..
..
..

python sicat.py -nm nmap_out_single --packetstorm

_._     _,-'""`-._
(,-.`._,'(       |\`-/|
    `-.-' \ )-`( , o o)
        `-    \`_`"'-
SiCat - The useful exploit finder
@justakazh (https://github.com/justakazh/sicat)

usage : sicat.py --help

[!] Only Supported for single host portscan result

```

other command, like in readme :
```
nmap -sV myip  -oX nmap_out | python sicat -nm --packetstorm
_._     _,-'""`-._
(,-.`._,'(       |\`-/|
    `-.-' \ )-`( , o o)
        `-    \`_`"'-
SiCat - The useful exploit finder
@justakazh (https://github.com/justakazh/sicat)

usage : sicat.py --help

usage: sicat.py [-h] [-k KEYWORD] [-kv KEYWORD_VERSION] [-nm NMAP] [--nvd] [--packetstorm] [--exploitdb] [--exploitalert] [--msfmodule] [-o OUTPUT] [-ot OUTPUT_TYPE]
sicat.py: error: argument -nm/--nmap: expected one argument
```

**Comment by justakazh** [comment]
The bug has been fixed, you can update the script and try again

Thanks.

**Comment by lay4onok** [comment]
however it's works in this input:

nmap -sV myIP -oX nmap_out | python .\sicat.py -nm nmap_out --nvd

_._     _,-'""`-._
(,-.`._,'(       |\`-/|
    `-.-' \ )-`( , o o)
        `-    \`_`"'-
SiCat - The useful exploit finder
@justakazh (https://github.com/justakazh/sicat)

usage : sicat.py --help

|
|> Starting with Keyword : FortiSSH
|----------------------------------------
|
|- No result in National Vulnearbility Database!
|
|> Starting with Keyword : SSL/TLS ClientHello
|----------------------------------------
|
|+ National Vulnearbility Database Result
|-----------------------------------------------
|- ID : CVE-2013-0440
|- Description : Unspecified vulnerability in the Java Runtime Environment (JRE) component in Oracle Java SE 7 through Update 11, 6 through Update 38, 5.0 through Update 38, and 1.4.2_40 and earlier, and OpenJDK 7, allows remote attackers to affect availability via vectors related to JSSE.  NOTE: the previous information is from the February 2013 CPU.  Oracle has not commented on claims from another vendor that this issue is related to CPU consumption in the SSL/TLS implementation via a large number of ClientHello packets that are not properly handled by (1) ClientHandshaker.java and (2) ServerHandshaker.java.
|- Link : https://nvd.nist.gov/vuln/detail/CVE-2013-0440
|
|
|- Total Result : 7 CVEs Found!
|
|> Starting with Keyword : Fortinet security device httpd
|----------------------------------------
|
|- No result in National Vulnearbility Database!

**Comment by justakazh** [comment]
@lay4onok you can use `nmap -sV 1.x.x.x --open -oX nmap_result.xml` 

thanks

**Comment by justakazh** [comment]
can i close this issue?

**Comment by lay4onok** [comment]
It's not me who opened it, but i've think you could
